name: Test
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 17
          cache: 'gradle'
      - uses: gradle/actions/wrapper-validation@v3
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - run: ./gradlew build --stacktrace

  buildNatives:
    strategy:
      matrix:
        target: [ x86_64, i686, aarch64 ]
    runs-on: windows-latest
    steps:
      # TODO: Fix macOS in future
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 17
          cache: 'gradle'
      - uses: gradle/actions/wrapper-validation@v3
      - run: ./gradlew build copyForNative --stacktrace
      - run: rustup target add ${{ matrix.target }}-pc-windows-msvc
      - name: Run Cargo
        run: cargo check --target ${{ matrix.target }}-pc-windows-msvc
        working-directory: ./native
